title: "Compact Treadmills For Apartments"
description: "Insights and guides about compact treadmills for apartments"
theme: jekyll-theme-minimal
url: "https://calcifergtp-glitch.github.io"
baseurl: "/compact-treadmills-for-apartments"
plugins:
  - jekyll-sitemap
