name: Daily content
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests
      - name: Generate post
        env:
          AFFILIATE_JSON: ${{ secrets.AFFILIATE_JSON }}
          CLICK_ROUTER_BASE: ${{ secrets.CLICK_ROUTER_BASE }}
        run: python scripts/generate_post.py
      - name: Commit & push
        run: |
          git config user.name "san-bot"
          git config user.email "bot@users.noreply.github.com"
          git add .
          git commit -m "daily post" || echo "nothing to commit"
          git push
